CREATE TABLE IF NOT EXISTS usuarios(
id SERIAL PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
email VARCHAR(150) NOT NULL UNIQUE,
senha VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS produtos(
id SERIAL PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
descricao TEXT, 
quantidade INTEGER NOT NULL DEFAULT 0,
preco REAL NOT NULL,
quantidade_minima INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS movimentacao_estoque(
id SERIAL PRIMARY KEY,
produto_id INTEGER NOT NULL,
tipo_movimentacao VARCHAR(25) NOT NULL, --' ENTRADA' OU 'SAIDA'
quantidade INTEGER NOT NULL,
data_movimentacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
usuario_id INTEGER,
FOREIGN KEY (produto_id) REFERENCES produtos(id),
FOREIGN KEY (usuario_id) REFERENCES usuarios(id)		
);